### ISSUE TITLE
Jenkins (2.248) or higher required

### ISSUE THREAD

**Issue by Drenjy** [tinexw/cdc-with-pact#11]
Processing provided DSL script
jenkins_1      | 2021-01-18 12:45:12.263+0000 [id=26]   WARNING j.util.groovy.GroovyHookScript#execute: Failed to run script file:/var/jenkins_home/init.groovy.d/create-jobs.groovy
jenkins_1      | javaposse.jobdsl.dsl.DslScriptException: (script, line 6) plugin 'workflow-aggregator' needs to be installed
jenkins_1      |        at javaposse.jobdsl.plugin.JenkinsJobManagement.failOrMarkBuildAsUnstable(JenkinsJobManagement.java:398)
jenkins_1      |        at javaposse.jobdsl.plugin.JenkinsJobManagement.requirePlugin(JenkinsJobManagement.java:285)
jenkins_1      |        at javaposse.jobdsl.dsl.JobManagement$requirePlugin.call(Unknown Source)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
jenkins_1      |        at javaposse.jobdsl.dsl.JobParent.pipelineJob(JobParent.groovy)
jenkins_1      |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1      |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1      |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1      |        at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1      |        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
jenkins_1      |        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
jenkins_1      |        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:384)
jenkins_1      |        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
jenkins_1      |        at script$_run_closure1.doCall(script:6)
jenkins_1      |        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jenkins_1      |        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
jenkins_1      |        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
jenkins_1      |        at java.lang.reflect.Method.invoke(Method.java:498)
jenkins_1      |        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
jenkins_1      |        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
jenkins_1      |        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
jenkins_1      |        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
jenkins_1      |        at groovy.lang.Closure.call(Closure.java:414)
jenkins_1      |        at groovy.lang.Closure.call(Closure.java:430)
jenkins_1      |        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
jenkins_1      |        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
jenkins_1      |        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2066)
jenkins_1      |        at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
jenkins_1      |        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

**Comment by tinexw** [comment]
Thanks for reporting the issue. I upgraded Jenkins to the latest LTS version. It should now work again. 
Will also apply the fix to the junit5 branch.
