### ISSUE TITLE
Update Jenkins

### ISSUE THREAD

**Issue by devtester-ro** [tinexw/cdc-with-pact#8]
Job creation will not be triggered because of old jenkins version.

**Comment by bit-jkraushaar** [comment]
Can be fixed by updating Jenkins to 2.242 and Git Plugin to 3.12.1 in infrastructure/jenkins/Dockerfile
I have opened a pull request for this: #10

**Comment by tinexw** [comment]
Merged the PR, thanks again for the contribution.
